import Link from "next/link"
import {
  ShieldCheck,
  Sparkles,
  Bot,
  Mail,
  CreditCard,
  Scale,
  UserCheck,
  Lock,
  RefreshCw,
  ArrowRight,
} from "lucide-react"

import { SiteHeader } from "@/components/site-header"
import { Button } from "@/components/ui/button"
import { getSession } from "@/lib/session"
import { getHeaderUsage } from "@/lib/header-usage"

export const metadata = {
  title: "Disclaimer",
  description:
    "Legal disclaimer for Thankful, an application developed and operated by Capstone Consulting.",
  alternates: { canonical: "/disclaimer" },
}

const LAST_UPDATED = "August 10, 2026"

const SECTIONS = [
  {
    icon: Sparkles,
    title: "General information only",
    body: "Thankful AI (the \u201cService\u201d) is provided by Capstone Consulting on an \u201cas is\u201d and \u201cas available\u201d basis, for general informational and personal-productivity purposes. While we work hard to keep the Service helpful and reliable, we make no warranties or representations of any kind, express or implied, about its accuracy, completeness, reliability, or availability. Your use of the Service is entirely at your own risk.",
  },
  {
    icon: Bot,
    title: "AI-generated content",
    body: "Thank-you notes, transcripts, gift lists, and other outputs are generated by automated AI systems and may contain errors, omissions, or misinterpretations, including of names, gifts, or spoken audio. All content is a draft for your review. You are solely responsible for reading, editing, and approving anything before you send, print, or share it. Capstone Consulting is not responsible for any content produced by the Service or for how it is used.",
  },
  {
    icon: Mail,
    title: "Delivery & third-party services",
    body: "The Service relies on third-party providers for functions such as email delivery, payment processing, hosting, and AI inference. We do not guarantee that emails will be delivered, received, or free of delay, nor do we control the practices of these third parties. Any issues arising from third-party services are governed by their own terms, and Capstone Consulting disclaims responsibility for their performance.",
  },
  {
    icon: CreditCard,
    title: "No professional advice",
    body: "Nothing provided through the Service constitutes legal, financial, etiquette, or other professional advice. The Service is a tool to assist you and should not be relied upon as a substitute for your own judgment or the advice of a qualified professional.",
  },
  {
    icon: Scale,
    title: "Limitation of liability",
    body: "To the fullest extent permitted by law, Capstone Consulting and its owners, employees, and affiliates shall not be liable for any direct, indirect, incidental, consequential, or punitive damages arising out of or related to your use of, or inability to use, the Service \u2014 including but not limited to errors in generated content, missed or mistaken messages, data loss, or interruptions of service.",
  },
  {
    icon: UserCheck,
    title: "Your responsibilities",
    body: "You are responsible for the accuracy of the information you provide, for obtaining any consent needed to record or process other people\u2019s information, and for ensuring your use of the Service complies with applicable laws. You agree to use the Service lawfully and not to rely on it for any purpose where an error could cause harm.",
  },
  {
    icon: Lock,
    title: "Privacy & your data",
    body: "Uploaded recordings are processed only to produce your transcript and are then removed; we aim to retain your personal media no longer than necessary for that purpose. You should avoid uploading sensitive information you would not want processed by automated systems, and you remain responsible for the content you submit.",
  },
  {
    icon: RefreshCw,
    title: "Changes to this disclaimer",
    body: "Capstone Consulting may update or modify this disclaimer, and the Service itself, at any time and without prior notice. Your continued use of the Service after any change constitutes acceptance of the revised disclaimer.",
  },
]

export default async function DisclaimerPage() {
  const session = await getSession()
  const usage = session?.user ? await getHeaderUsage() : null

  return (
    <div className="min-h-svh">
      <SiteHeader user={session?.user ?? null} usage={usage} />
      <main className="mx-auto w-full max-w-3xl px-4 py-12 sm:px-6 sm:py-16">
        {/* Hero */}
        <header className="mb-12 flex flex-col gap-4">
          <span className="inline-flex w-fit items-center gap-1.5 rounded-full bg-secondary px-3 py-1 text-xs font-medium text-secondary-foreground">
            <ShieldCheck className="size-3.5 text-primary" />
            Legal
          </span>
          <h1 className="font-serif text-4xl font-semibold tracking-tight text-balance sm:text-5xl">
            Disclaimer
          </h1>
          <p className="text-base leading-relaxed text-muted-foreground text-pretty">
            {"Thankful AI is an application developed and operated by "}
            <a
              href="https://capstoneconsulting.co"
              target="_blank"
              rel="noopener noreferrer"
              className="font-medium text-primary underline-offset-4 hover:underline"
            >
              Capstone Consulting
            </a>
            {
              ". Please read this disclaimer carefully before using the Service."
            }
          </p>
          <p className="text-xs text-muted-foreground/70">
            Last updated: {LAST_UPDATED}
          </p>
        </header>

        {/* Sections */}
        <div className="flex flex-col gap-4">
          {SECTIONS.map((s) => (
            <section
              key={s.title}
              className="flex gap-4 rounded-2xl border bg-card p-6"
            >
              <span className="flex size-11 shrink-0 items-center justify-center rounded-xl bg-secondary text-secondary-foreground">
                <s.icon className="size-5 text-primary" />
              </span>
              <div className="flex flex-col gap-1.5">
                <h2 className="font-serif text-lg font-semibold leading-tight">
                  {s.title}
                </h2>
                <p className="text-sm leading-relaxed text-muted-foreground text-pretty">
                  {s.body}
                </p>
              </div>
            </section>
          ))}
        </div>

        {/* Contact / close */}
        <section className="mt-10 rounded-2xl border bg-secondary/50 p-6 text-center">
          <p className="text-sm leading-relaxed text-muted-foreground text-pretty">
            {"Questions about this disclaimer? Reach out to Capstone Consulting at "}
            <a
              href="mailto:hello@capstoneconsulting.co"
              className="font-medium text-primary underline-offset-4 hover:underline"
            >
              hello@capstoneconsulting.co
            </a>
            .
          </p>
          <div className="mt-5">
            <Button
              variant="outline"
              nativeButton={false}
              render={<Link href="/how-to" />}
            >
              How to use Thankful AI
              <ArrowRight data-icon="inline-end" />
            </Button>
          </div>
        </section>
      </main>
    </div>
  )
}
